### ISSUE TITLE
Ranged Weapon Speed Calculation

### ISSUE THREAD

**Issue by Smothmoth** [n0q/hackmaster5e-fvtt#304] opened 2024-04-25 01:58 UTC
There seems to be something going wrong with the way total speed for ranged is being calculated at the moment. While setting up a new ranged weapon for an NPC boss, I notice that altering load/draw/aim/fire values manually gives very weird and seemingly random results as to what the new Total Speed value becomes.

**Comment by n0q** [comment] 2024-04-25 02:03
That's interesting. Is it only happening with beasts? What sort of ranged weapon, and does the beast have a speed bonus? I'll try to reproduce this.

**Comment by n0q** [comment] 2024-04-25 09:26
It looks like something rotten has snuck into the timing code, somewhere along the way. I'm able to reproduce this. Will make sure to get it done in the next release. Thanks for the report!

**Comment by n0q** [comment] 2024-04-25 10:26
Seems like the sheet listener for this logic never actually worked correctly. You were observing the result of saving the new timing incorrectly, and then summing up the incorrect data. I can see how this would've looked random. This is resolved. It'll be fixed in the next update. Thanks again!

**Closed by n0q** 2024-04-25 10:26 UTC
Labels: confirmed-bug

**Comment by Smothmoth** [comment] 2024-04-25 10:33
Happy to be of help
